### ISSUE TITLE
Is there a reason to wait for the latest minor version to add a new tag?

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/lts#11]
Hi @nicolas-grekas 

Following the (already closed) issue https://github.com/symfony/lts/issues/9

My concern on keep the `@dev` package until the Symfony community releases the version 4.4.0 is that I need to update my `composer.json` file to allow `dev` packages (for a long time), and this might have a direct impact on other libraries (not just Symfony) that could be using `master` branches too instead of stable versions, unless I am explicit with the settings on my Composer file.

I means that I might have a project with multiple dependencies on `dev` versions instead of stable releases that have been tagged.

Thanks for your understanding on this.

Best,

**Comment by alexisLefebvre** [comment]
Could you please show the content of your `composer.json`?

> I need to update my composer.json file to allow dev packages (for a long time), and this might have a direct impact on other libraries (not just Symfony)

Do you use `"minimum-stability": "dev"`? You will have more stables versions if you use `@dev` for the packages that require unstable versions.

**Comment by nicolas-grekas** [comment]
Sorry I missed answering. Yes, there's a reason: we don't know the list of components that will exist in latest version of 4.*

**Comment by DavidGarciaCat** [comment]
Thanks for your clarification
